config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :customers, except: [:new] do
    resources :vehicles, only: [:new, :create]
  end
  resources :employees do
    resources :repair_orders, only: [:show, :index]
  end
  resources :jobs, except: [:new, :edit, :index, :show]
  resources :repair_orders, except: [:edit, :update] do
    resources :jobs, only: [:new, :edit]
  end
  resources :vehicles, except: [:show, :new]

  get '/signup' => 'customers#new', as: 'signup'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebook_create'
  get '/login/employee' => 'sessions#new_employee', as: 'login_employee'
  post '/login/employee' => 'sessions#create_employee'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :repair_orders
    has_many :vehicles, through: :repair_orders
    has_many :jobs, through: :repair_orders
    has_many :customers, through: :repair_orders
    
    has_secure_password

    validates :name, :worker_number, :job_title, presence: true
    validates :worker_number, uniqueness: true
    validates :password, confirmation: true
    validates :password_confirmation, presence: true, on: :create
    validates :worker_number, length: { is: 4 }

    scope :administrators, -> { where(admin: true) }


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    
    before_action :check_logged_in
    before_action :check_employee
    before_action :get_employee, except: [:new, :create, :index]


    def new
        admin
        @employee = Employee.new
    end

    def create
        admin
        @employee = Employee.new(employee_params)
        if @employee.save
            redirect_to employee_path(@employee)
        else
            render :new
        end
    end

    def show
    end

    def index
        @administrators = Employee.administrators
        @employees = Employee.all
    end

    def edit
        admin
    end

    def update
        admin
        if @employee.update(employee_params)
            redirect_to employee_path(@employee)
        else
            render :new
        end
    end

    def destroy
        admin
        @employee.destroy
        redirect_to employees_path
    end

    private

    def employee_params
        params.require(:employee).permit(:name, :worker_number, :job_title, :password, :password_confirmation, :admin)
    end

    def get_employee
        if @employee = Employee.find_by(id: params[:id])
           return @employee
        else
           flash[:errors] = "That employee does not work here"
           redirect_to employees_path
        end
     end

     def admin
        if current_user.admin == nil
            redirect_to employee_path(current_user)
        end
     end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: employee, local: true do |f| %>

<div class="form_box">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="form_box">
  <%= f.label :worker_number %>
  <%= f.text_field :worker_number %>
</div>

<div class="form_box">
  <%= f.label :job_title %>
  <%= f.text_field :job_title %>
</div>

<div class="form_box">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

<div class="form_box">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

  <%= f.label :admin %>
  <%= f.check_box :admin %>

  <%= f.submit %>

<% end %>

app/views/employees/edit.html.erb
<%= render partial: "form", locals: {employee: @employee} %>


<%= render partial: "shared/error", locals: {model: @employee} %>

app/views/employees/index.html.erb
 <%= link_to "Hire", new_employee_path %>

<div class="employee-box">
  <% @administrators.each do |admin| %>
      <%= admin.name %>
      <%= admin.job_title %>
      <%= admin.worker_number %>
  <% end %>
</div>

<% @employees.each do |emp| %>
  <div class="employee-box">
    <h3><%= link_to "#{emp.name}", employee_path(emp) %></h3>
    <%= emp.job_title %>
    <%= emp.worker_number %>
    <div>
      <% if current_user.admin == true %>
        <%= link_to "Hire", new_employee_path %>
        <%= link_to "Edit", edit_employee_path(emp) %>
        <%= button_to "Fire", emp, method: :delete, data: { confirm: "Really?" } %>
      <% end %>
    <div>
  <div>
<% end %>

app/views/employees/new.html.erb
<%= render partial: "form", locals: {employee: @employee} %>

<%= render partial: "shared/error", locals: {model: @employee} %>

app/views/employees/show.html.erb
<h3><%= @employee.name %> </h3>
  <%= @employee.job_title %>

<% if current_user.admin == true %>
  <%= button_to "Fire", @employee, method: :delete, data: { confirm: "Really?" } %>
  <%= link_to "Edit", edit_employee_path(@employee) %>
<% end %>