config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :customers, except: [:new] do
    resources :vehicles, only: [:new, :create]
  end
  resources :employees do
    resources :repair_orders, only: [:show, :index]
  end
  resources :jobs, except: [:new, :edit, :index, :show]
  resources :repair_orders, except: [:edit, :update] do
    resources :jobs, only: [:new, :edit]
  end
  resources :vehicles, except: [:show, :new]

  get '/signup' => 'customers#new', as: 'signup'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebook_create'
  get '/login/employee' => 'sessions#new_employee', as: 'login_employee'
  post '/login/employee' => 'sessions#create_employee'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :repair_orders
    has_many :vehicles, dependent: :destroy
    has_many :jobs, through: :repair_orders
    has_many :employees, through: :repair_orders

    has_secure_password


    validates :name, presence: true
    validates :email, :phone_number, uniqueness: true
    validates :phone_number, length: {is: 10}, allow_blank: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :password, confirmation: true, on: :create
    validates :password_confirmation, presence: true, on: :create


end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :check_logged_in, except: [:new, :index, :create]
    before_action :get_customer, except: [:new, :index, :create]
    before_action :invalid_customer, except: [:new, :index, :create]
    def new
        @customer = Customer.new
    end

    def create
        @customer = Customer.new(customer_params)
        if @customer.save
            log_in(@customer)
            redirect_to customer_path(@customer)
        else
            render :new
        end
    end

    def index
        @customers = Customer.all
    end

    def show
    end

    def edit
    end

    def update 
        if @customer.update(customer_params)
            redirect_to customer_path(@customer)
        else
            render :edit
        end
    end

    def destroy
        if @customer
          @customer.destroy
          redirect_to customers_path
        end
    end

    private

    def customer_params
        params.require(:customer).permit(:name, :phone_number, :email, :password, :password_confirmation)
    end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with model: customer, local: true do |f| %>

<div class="form_box">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="form_box">
  <%= f.label :phone_number %>
  <%= f.number_field :phone_number %>
</div>

<div class="form_box">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div class="form_box">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

<div class="form_box">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

  <%= f.submit %>

<% end %>

app/views/customers/edit.html.erb
<%= render partial: "form", locals: {customer: @customer} %>


<%= render partial: "shared/error", locals: {model: @customer} %>

app/views/customers/index.html.erb
<% @customers.each do |cust| %>
  <div class="customer-box">
    <h3><%= link_to "#{cust.name}", customer_path(cust) %></h3>
    <% if current_user == cust || current_user.worker_number != nil %>
      <%= button_to "Delete", cust, method: :delete, data: { confirm: "Really?" } %>
      <%= link_to "Edit", edit_customer_path(cust), method: :get %>
    <% end %>
  <div>
<% end %>

app/views/customers/new.html.erb
<%= render partial: "form", locals: {customer: @customer} %>

<%= render partial: "shared/error", locals: {model: @customer} %>

app/views/customers/show.html.erb
<h3><%= @customer.name %> </h3>
  <p><%= @customer.phone_number %></p>
  <p><%= @customer.email %></p>
  <% if current_user == @customer || current_user.worker_number != nil %>
  <%= button_to "Delete", @customer, method: :delete, data: { confirm: "Really?" } %>
  <%= link_to "Edit", edit_customer_path(@customer) %>
  <% end %>
    <div>
      <h4> <%= @customer.name%>'s vehicles </h4>
      <% @customer.vehicles.each do |veh| %>
        <p><%= veh.make %></p>
        <p><%= veh.model %></p>
      <% end %>
    </div>