config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :customers, except: [:new] do
    resources :vehicles, only: [:new, :create]
  end
  resources :employees do
    resources :repair_orders, only: [:show, :index]
  end
  resources :jobs, except: [:new, :edit, :index, :show]
  resources :repair_orders, except: [:edit, :update] do
    resources :jobs, only: [:new, :edit]
  end
  resources :vehicles, except: [:show, :new]

  get '/signup' => 'customers#new', as: 'signup'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebook_create'
  get '/login/employee' => 'sessions#new_employee', as: 'login_employee'
  post '/login/employee' => 'sessions#create_employee'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/repair_order.rb
class RepairOrder < ApplicationRecord
    belongs_to :employee
    belongs_to :vehicle
    belongs_to :customer
    has_many :jobs, dependent: :destroy

    validates_associated :employee, :vehicle, :customer

    

end

app/controllers/repair_orders_controller.rb
class RepairOrdersController < ApplicationController

    before_action :check_logged_in, except: [:index]
    before_action :check_employee, except: [:index, :show]

    def new
        @repair_order = RepairOrder.new
        2.times { @repair_order.jobs.build }
    end

    def create
        @repair_order = RepairOrder.new
        @repair_order.vehicle = Vehicle.find_by(vin: repair_order_params[:vin_number])
        @repair_order.employee = current_user
        if @repair_order.vehicle
          @repair_order.customer = @repair_order.vehicle.customer
        end
        
        if @repair_order.save
            redirect_to new_repair_order_job_path(@repair_order)
        else
            flash[:error] = "#{@repair_order.errors.full_messages}"
            render :new
        end
    end

    def index
        if params[:employee_id]
          @repair_orders = Employee.find(params[:employee_id]).repair_orders
        else
          @repair_orders = RepairOrder.all
        end
    end

    def show
          @repair_order = RepairOrder.find(params[:id])
          @veh = @repair_order.vehicle
          @cust = @repair_order.vehicle.customer
          @jobs = @repair_order.jobs
    end

    def destroy
        @repair_order = RepairOrder.find(params[:id]).delete
        redirect_to repair_orders_path
    end

    private

    def repair_order_params
        params.require(:repair_order).permit(:vin_number, :worker_number, jobs_attributes:[
            :concern
        ])

    end
end

app/helpers/repair_orders_helper.rb
module RepairOrdersHelper
end

app/views/repair_orders/index.html.erb
  <% @repair_orders.each do |ro| %>
  <div>
    <%= link_to "#{ro.id}", repair_order_path(ro) %>
    <%= ro.vehicle.customer.name %>
    <%= "#{ro.vehicle.make} - #{ro.vehicle.model}" %>
    <% if employee? %>
      <%= button_to "Delete", ro, method: :delete, data: { confirm: "Really?" } %>
    <% end %>
    </div>
  <% end %>

app/views/repair_orders/new.html.erb
<%= form_with model: @repair_order, local: true do |f| %>

<div class="form_box">
  <%= f.label :vin_number %>
  <%= f.text_field :vin_number %>
</div>

<%= f.submit %>
<% end %>

app/views/repair_orders/show.html.erb
<div>
  <p>Repair Order number <%= @repair_order.id %> </p>
</div>

    <% if employee? %>
      <%= button_to "Delete", @repair_order, method: :delete, data: { confirm: "Really?" } %>
    <% end %>

<div>
  <p>Customer: <%= @cust.name %> </p>
</div>

<div><h3> Vehicle info </h3>
  <div>
    <p> Vehicle Make:<%= @veh.make %></p>
  </div>
  
  <div>
    <p> Vehicle Model: <%= @veh.model %></p>
  </div>
  
  <div>
    <p> Vehicle Miles: <%= @veh.miles %></p>
  </div>
</div>

<div>
  <% @jobs.each do |j| %>
    <div> <h3> Jobs </h3>
      <p> Concern: <%= j.concern %></p>
      <p> Complete? <%= j.completed %> </p>
    </div>
  <% end %>
</div>