config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :customers, except: [:new] do
    resources :vehicles, only: [:new, :create]
  end
  resources :employees do
    resources :repair_orders, only: [:show, :index]
  end
  resources :jobs, except: [:new, :edit, :index, :show]
  resources :repair_orders, except: [:edit, :update] do
    resources :jobs, only: [:new, :edit]
  end
  resources :vehicles, except: [:show, :new]

  get '/signup' => 'customers#new', as: 'signup'

  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#facebook_create'
  get '/login/employee' => 'sessions#new_employee', as: 'login_employee'
  post '/login/employee' => 'sessions#create_employee'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_logged_in_employee_navebar.html.erb
<p><%= button_to "Logout", logout_path, method: :delete %>
<%= link_to " employees ", employees_path %>
<%= link_to " all repair orders ", repair_orders_path %>
<%= link_to " vehicles ", vehicles_path %>
<%= link_to " create a new repair order ", new_repair_order_path %>
<%= link_to " customers ", customers_path %>
<%= link_to " your repair orders ", employee_repair_orders_path(current_user) %></p>

app/views/layouts/_logged_in_navbar.html.erb
<p><%= button_to "Logout", logout_path, method: :delete %>
<%= link_to "your info", customer_path(current_user) %>
<%= link_to "in the shop now", repair_orders_path %>
<%= link_to "Add a vehicle", new_customer_vehicle_path(current_user) %></p>

app/views/layouts/_logged_out_navbar.html.erb
<p><%= link_to "log in", login_path %>
<%= link_to "sign up", signup_path %>
<%= link_to('Log in with Facebook!', '/auth/facebook') %>
<%= link_to "employee log in", login_employee_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatironDmsRailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <header>
    <%= navbar %>
    <div class="errors">
      <% flash.each do |k, v| %>
        <p><%= v %></p>
      <% end %>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/logged_out_navbar.html.erb
<%= link_to "log in", login_path %>
<%= link_to "sign up", signup_path %>